const PREFIX = "SERVER_";
module.exports = {
    CREATE_GAME_SUCCESS: `${PREFIX}CREATE_GAME_SUCCESS`,
    JOIN_GAME_SUCCESS: `${PREFIX}JOIN_GAME_SUCCESS`,
    ENOUGH_PLAYERS: `${PREFIX}ENOUGH_PLAYERS`,
    OPPONENT_READY: `${PREFIX}OPPONENT_READY`,
    START_GAME: `${PREFIX}START_GAME`,
    PAUSE_GAME: `${PREFIX}PAUSE_GAME`,
    OPPONENT_INCREASE_MATCH_COUNT: `${PREFIX}OPPONENT_INCREASE_MATCH_COUNT`,
    OPPONENT_LEVEL_UP: `${PREFIX}OPPONENT_LEVEL_UP`,
    OPPONENT_FINISH_GAME: `${PREFIX}OPPONENT_FINISH_GAME`,
    PLAYER_WIN: `${PREFIX}PLAYER_WIN`,

    GAME_ERROR: `${PREFIX}GAME_ERROR`,
};